local Events = dofile('Preymonition/Scripts/preymonition/events.lua')
local queue = Events.new(2)
local first = queue:push('show', 'one')
local replacement = queue:push('show', 'one')
assert(replacement.sequence > first.sequence and #queue.items == 1, 'consecutive duplicates must coalesce')
queue:push('clear', 'one')
queue:push('show', 'two')
assert(#queue.items == 2 and queue.dropped == 1, 'queue must remain bounded')
local items = queue:drain()
assert(items[1].kind == 'clear' and items[2].path == 'two', 'surviving event order must be preserved')
assert(#queue.items == 0)
queue:push('combat_end', 'combat')
queue:push('show', 'late')
queue:push('show', 'newer')
items = queue:drain()
assert(items[1].kind == 'combat_end' and items[2].path == 'newer', 'combat end must survive queue pressure')
queue:push('clear', 'other')
queue:clear()
assert(#queue.items == 0)
print('PASS: bounded event queue, duplicate coalescing, ordering, and clearing')
